kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"
        "service-account-key-file": "/etc/kubernetes/pki/sa.pub"
        "service-account-issuer": "api"
        "service-account-api-audiences": "api,vault,factors"
